swagger: '2.0'
info:
  title: swAuth
  description: ""
  version: "1.0.0"
# the domain of the service
host: 
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /checkToken:
    get:
      summary: Vérification d'un token.
      description: 
        Vérification d'un token.
      parameters:
        - token: token à vérifier (clé -> token)
      responses:
        200:
          cas1: ok en cas de token valide FORMAT JSON -> {'reponse':'ok'}
          cas2: ko en cas de token invalide FORMAT JSON -> {'reponse':'ko'}
  /getTokens:
    get:
      summary: Récupération des tokens d'un utilisateur
      description:
        Récupération des tokens d'un utilisateur
      parameters:
        id_user: id de l'utilisateur (clé -> token)
      tags:
        - Estimates
      responses:
        200:
          cas1: envoie d'un tableau contenant les tokens de l'utilisateur FORMAT JSON -> {'reponse':'ok'}
          cas2: ko FORMAT JSON -> {'reponse':'ko'}
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'