# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Xtrempubsub 
  description: API Xtrem projet 3A Plateformes mobiles
  version: "1.0.0"
# the domain of the service TODO
host: localhost
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths

produces:
  - application/json
paths:
    /subChannel/topic:
      get:
        summary: Subscription to a channel
        parameters:
         - name: topicName
           in: query
           description: topic subsciption asked
           required: true
           type: string
        responses:
          200:
            description: Routes to manage subscription to a channel
            schema:
              $ref: '#/definitions/ChannelName'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    /subChannel/geoloc:
      get:
        summary: get geoloc subscription
        parameters:
          - name: geolocData
            in: body
            description: geolocation subscription asked
            required: true
            schema: 
              $ref: '#/definitions/GeolocPerimeter'
        responses:
          200:
            description: Routes to manage subscription to a channel
            schema:
              $ref: '#/definitions/ChannelName'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
    /newPost:
      get:
        summary: New post
        parameters:
          - name: activity
            in: body
            description: new post (topic name, geopositions data)
            required: true
            schema: 
              $ref: '#/definitions/Activity'
        responses:
          200:
            description: Routes to manage subscription to a channel
            schema:
              $ref: '#/definitions/AlertChannelRoutes'
          default:
            description: Unexpected error
            schema:
              $ref: '#/definitions/Error'
definitions:
  Geolocation:
    type: object
    properties:
      latitude:
        type: number
        format: double
        description: Latitude of the activity's location
      longitude:
        type: number
        format: double
        description: Longitude of the activity's location
  Activity:
      type: object
      properties:
        topic:
          type: string
          description: Topic of the activity
        date:
          type: string
          description: Date of the activity
        geolocation:
          $ref: '#/definitions/Geolocation'
        popularity:
          type: number
          format: integer
          description: Popularity of the activity
  GeolocPerimeter:
      type: object
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        perimeter:
          type: number
          format: double
  ChannelName:
    type: object
    properties:
      channelname:
        type: string
        description: Name of channel
  AlertChannelRoutes:
    properties:
      subscribeRoute:
        type: string
        description: Route to subscribe to a requested channel
      unsubscribeRoute:
        type: string
        description: Route to unsubscribe to a requested channel
      data:
        $ref: '#/definitions/Activity'
  Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string