#!/usr/bin/env python
# -*- coding: utf-8 -*-
import time, sys, json, requests, redis
reload(sys) # ugly hack to access sys.setdefaultencoding
sys.setdefaultencoding('utf-8')


# REDIS
redisClient = redis.StrictRedis(host='localhost', port=6379, db=0)
channel = redisClient.pubsub()

while True:
    redisClient.publish("test", 'toto')
    time.sleep(0.5)
    
while True:
    message = p.get_message()
    if message:
        print "Subscriber: %s" % message['data']
    time.sleep(1)

# AJAX REQ

param = {'channelName': 'grabolosa'}
response = requests.get('http://127.0.0.1:3000/subChannel', param)

