# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TLite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TLite
    pod 'SwiftyJSON'
    pod 'Alamofire'
    
  target 'TLiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TLiteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
